name: Validar y Desplegar a Netlify

on:
  push:
    branches:
      - main

jobs:
  # Trabajo 1: Se encarga de la validación
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas y validaciones
        run: npm test

  # Trabajo 2: Se encarga del despliegue, pero DEPENDE del éxito del anterior
  deploy:
    runs-on: ubuntu-latest
    needs: test # <--- ESTO GARANTIZA QUE SI 'TEST' FALLA, ESTE JOB SE CANCELA
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy automático por commit ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
